version: '2'
services:
    account-service-db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=account-service

    account-service:
        image: zhongwei/account-service
        ports:
            - "8080:8080"
        links:
            - account-service-db:mysql
