version: '2'

services:
    account-service-db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=account-service
        networks:
            microservices4j:
                aliases:
                    - mysql

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            microservices4j:
                aliases:
                    - redis

    account-service:
        depends_on:
            - account-service-db
            - redis
        restart: always
        image: zhongwei/account-service
        ports:
            - "8080:8080"
        networks:
            microservices4j:

networks:
    microservices4j:
        driver: bridge
